language: node_js
node_js: node
script: "npm run cover"
# Send coverage report to coveralls.io
after_script: "cat ./build/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
notifications:
  email: false
branches:
  only:
  - master
